import { Poppins } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import {  useSession } from "next-auth/react";
import {useEffect} from "react"
import { signOut } from "next-auth/react"
import FrameSetHeaderButtons from "../components/FrameSetHeaderButtons/FrameSetHeaderButtons";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export default function Home(){
  const { data: session } = useSession()
  useEffect(()=>{
    console.log({session});
  });

  return (
    <div className={styles.landingPage}>
      <main className={styles.previewsTestingLink}>
        <section className={styles.frameParent}>
          <div className={styles.frameWithHeadingsParent}>
            <div className={styles.frameWithHeadings}>
              <h1 className={styles.heading1}>Resource Hub</h1>
            </div>
            <h2 className={styles.fewAboutLines}>
              The perfect destination for ethusiasts. The vast collection of resources has been crafted just for you.
            </h2>
          </div>
          {/* <div className={styles.form}>
            <div className={styles.chidigoodplacecom}>chidi@goodplace.com</div>
            <button className={styles.button}>
              <div className={styles.getStarted}>Get started</div>
            </button>
          </div> */}
        </section>
        {/* <section className={styles.lovedByDevelopersAndMarketParent}>
          <div className={styles.lovedByDevelopers}>
            Loved by developers and marketers alike
          </div>
          <div className={styles.divindexpageStyleddiv16Rd}>
            <h1 className={styles.dummy}>DUMMY</h1>
            <h1 className={styles.dummy}>DUMMY</h1>
            <h1 className={styles.dummy}>DUMMY</h1>
            <h1 className={styles.dummy}>DUMMY</h1>
          </div>
        </section> */}
        <FrameSetHeaderButtons icon="https://res.cloudinary.com/dhry5xscm/image/upload/v1709075360/resource-hub/HTML5_Logo_zeyrgi.svg" dest="/HTML" title={"HyperText Markup Language"} date={"28/02/2024"} author={"Barnil Sarma"} about={"A beginner's guide to HTML, TAGS, ATTRIBUTES and many more!!"} />
        <FrameSetHeaderButtons icon="https://res.cloudinary.com/dhry5xscm/image/upload/v1709084079/resource-hub/CSS3_logo_and_wordmark_scvfqa.svg" dest="/CSS" title={"Cascading Stylesheet"} date={"28/02/2024"} author={"Barnil Sarma"} about={"A beginner's guide to CSS, styling, animation, transitions and many more!!"} />
      </main>
    </div>
  );

  // if (session) {
  //   const { user } = session
  //   const { email, name, image } = user

  //   return (
  //     <div>
  //       <p>Email: {email}</p>
  //       <p>Name: {name}</p>
  //       <img src={image} />
  //       <button onClick={() => signOut()}>Sign out</button>
  //     </div>
  //   )
  
}
// export default function Home() {
//   const {data:session} = useSession()
//   if(session){
    
//   }
//   useEffect(()=>{
//     console.log("Testing");
//   },[]);
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={`${styles.main} ${poppins.className}`}>{session.user}</main>

//       {session ? User({session}):Guest()}
//     </>
//   );
// }

// const User = ({session}) =>{
// //  <h1>{{session}?.user?.name}</h1>
//  console.log({session})
// }


// const Guest = () =>{
//   return(
//     <>
//     <h2>Unknown</h2>
//     <h3>Unknown</h3>
//     </>
//   )
// }
