import Head from "next/head";
import { Poppins } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import {  useSession } from "next-auth/react";
import {useEffect} from "react"
import { signOut } from "next-auth/react"


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export default function Home(){
  const { data: session } = useSession()
  useEffect(()=>{
    console.log({session});
  });

  if (session) {
    const { user } = session
    const { email, name, image } = user

    return (
      <div>
        <p>Email: {email}</p>
        <p>Name: {name}</p>
        <img src={image} />
        <button onClick={() => signOut()}>Sign out</button>
      </div>
    )

  return <p>User is not logged in.</p>
}
// export default function Home() {
//   const {data:session} = useSession()
//   if(session){
    
//   }
//   useEffect(()=>{
//     console.log("Testing");
//   },[]);
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={`${styles.main} ${poppins.className}`}>{session.user}</main>

//       {session ? User({session}):Guest()}
//     </>
//   );
// }

// const User = ({session}) =>{
// //  <h1>{{session}?.user?.name}</h1>
//  console.log({session})
// }


// const Guest = () =>{
//   return(
//     <>
//     <h2>Unknown</h2>
//     <h3>Unknown</h3>
//     </>
//   )
// }
}